Document: aptsh
Title: Debian aptsh Manual
Author: <insert document author here>
Abstract: This manual describes what aptsh is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/aptsh/aptsh.sgml.gz

Format: postscript
Files: /usr/share/doc/aptsh/aptsh.ps.gz

Format: text
Files: /usr/share/doc/aptsh/aptsh.text.gz

Format: HTML
Index: /usr/share/doc/aptsh/html/index.html
Files: /usr/share/doc/aptsh/html/*.html

  
