#!/usr/bin/perl
# Author: Marcin Wrochniak (wrochniak@gmail.com)
# Distributed under GPL.
# Made for Aptsh Project.
# Transforms groff manpage to html

$path = $ARGV[0];
$out = $path.'.html';

if (! open(FILE, $path)) {
	die("Can't open file!\n");
}	

open(OUT, $out);

print '<html><body style="background: silver;"><div style="width: 42em; background: white; padding: 1em;">';

while ($z = <FILE>) {
	$z =~ s/\.RS/<div>/g;
	$z =~ s/\.RE/<\/div>/g;
	$z =~ s/^\.TH(.*)(\d).*\"(.*)\".*\"(.*)\".*$/<h3>\1 (\2)<\/h3>\n<br><i>\3<\/i>\n<br><i>\4<\/i>/;
	$z =~ s/^\.SH(.*)$/<h4>\1<\/h4>/;
	$z =~ s/^\.I(.*)$/<i>\1<\/i>/;
	$z =~ s/\.TP/<br>/g;
	$z =~ s/\.B(.*)$/<b>\1<\/b>/;
	$z =~ s/\.PP(.*)$/<h5>\1<\/h5>/;
	print $z;
}

printf '</div><div style="font-size: 6pt;">Generated by <a href="http://svn.berlios.de/viewcvs/aptsh/tools/jeb.pl">jeb.pl</a></div></body></html>';
